### ISSUE TITLE
Risolto problema d'installazione

### ISSUE THREAD

**Issue by MicGeos** [geognu/topog4qgis#3]
Il problema d'installazione l'ho risolto andando a modificare il nome della cartella del plugin. Manualmente ho tolto la dicitura "master" facendo rimanere soltanto "topog4qgis". In questo modo il plugin si avvia. Ciao

**Comment by geognu** [comment]
Installando dal plugin manager di QGis 2.x il problema non viene rilevato. Puoi spiegare i passaggi che hanno condotto all'errore, specificando la piattaforma e la versione di QGis in uso?

**Comment by MicGeos** [comment]
Sistema operativo Win 7 PRO sp1 64bit. QGIS 2.2.0 Valmiera. Invece il problema mi è stato rilevato installando il plugin dal plugin manager di QGIS 2.2.0. Diversamente, scaricando il plugin dalla home e inserendolo manualmente nella cartella corrispondente di QGIS il plugin si carica. Dimenticavo che bisogna avere l'accortezza di eliminare la dicitura master da topog4qgis.

**Comment by geognu** [comment]
Il problema sembra essere locale. Su win 8.1 stessa versione nessun problema. Per ora chiudo la segnalazione.
